'use client';

/**
 * Component: InterventionCard.tsx
 * Description: Displays proactive smart coaching advice generated by decay detection,
 * accompanied by user feedback buttons (helpful, not helpful, dismissed) to feed into
 * the recommendation improvement loop.
 */

import React, { useState } from 'react';
import {
  Intervention,
  SuggestionType,
  UserResponse,
} from '@/lib/supabase/types';
import {
  SplitSquareVertical,
  Coffee,
  Shuffle,
  Award,
  ThumbsUp,
  ThumbsDown,
  X,
  Check,
  Sparkles,
} from 'lucide-react';

interface InterventionCardProps {
  intervention: Intervention;
  projectName?: string;
  onFeedbackUpdated?: (id: string, response: UserResponse) => void;
}

export const InterventionCard: React.FC<InterventionCardProps> = ({
  intervention,
  projectName,
  onFeedbackUpdated,
}) => {
  const [currentResponse, setCurrentResponse] = useState<UserResponse | null>(
    intervention.user_response || null
  );
  const [isUpdating, setIsUpdating] = useState<boolean>(false);

  // Badge details mapping
  const getBadgeConfig = (type: SuggestionType) => {
    switch (type) {
      case 'break_task':
        return {
          label: 'Chia nhỏ nhiệm vụ (Micro-step)',
          color: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
          icon: SplitSquareVertical,
        };
      case 'take_break':
        return {
          label: 'Nghỉ ngơi phục hồi (Acute Burnout)',
          color: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
          icon: Coffee,
        };
      case 'change_approach':
        return {
          label: 'Tối ưu nhịp độ (Consistency)',
          color: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
          icon: Shuffle,
        };
      case 'celebrate_progress':
        return {
          label: 'Ghi nhận cột mốc (Hedonic Adaptation)',
          color: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
          icon: Award,
        };
    }
  };

  const badge = getBadgeConfig(intervention.suggestion_type);
  const IconComponent = badge.icon;

  const handleFeedback = async (response: UserResponse) => {
    setIsUpdating(true);
    try {
      const res = await fetch(`/api/interventions/${intervention.id}/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ response }),
      });

      if (res.ok) {
        setCurrentResponse(response);
        if (onFeedbackUpdated) {
          onFeedbackUpdated(intervention.id, response);
        }
      }
    } catch (err) {
      console.error('Error submitting feedback:', err);
    } finally {
      setIsUpdating(false);
    }
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 hover:border-slate-700/80 rounded-2xl p-5 shadow-lg transition-all relative overflow-hidden">
      {/* Decorative indicator line */}
      <div
        className={`absolute top-0 left-0 bottom-0 w-1.5 ${
          intervention.suggestion_type === 'take_break'
            ? 'bg-rose-500'
            : intervention.suggestion_type === 'break_task'
            ? 'bg-indigo-500'
            : intervention.suggestion_type === 'celebrate_progress'
            ? 'bg-emerald-500'
            : 'bg-amber-500'
        }`}
      />

      <div className="pl-2">
        {/* Header */}
        <div className="flex flex-wrap items-center justify-between gap-2 mb-2.5">
          <div className="flex items-center gap-2">
            <span
              className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border ${badge.color}`}
            >
              <IconComponent className="w-3.5 h-3.5" />
              {badge.label}
            </span>
            {intervention.tone && (
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-800 text-slate-400 border border-slate-700/60 font-medium">
                {intervention.tone === 'scientific'
                  ? '🔬 Khoa học hành vi'
                  : intervention.tone === 'compassionate'
                  ? '🌱 Đồng cảm sâu sắc'
                  : '⚡ Hành động nhanh'}
              </span>
            )}
            {projectName && (
              <span className="text-xs text-slate-400">
                cho <strong className="text-slate-300">{projectName}</strong>
              </span>
            )}
          </div>

          <span className="text-[11px] text-slate-500">
            {new Date(intervention.created_at).toLocaleDateString('vi-VN', {
              month: 'short',
              day: 'numeric',
              hour: '2-digit',
              minute: '2-digit',
            })}
          </span>
        </div>

        {/* Message body */}
        <p className="text-xs md:text-sm text-slate-200 leading-relaxed font-normal mb-3">
          {intervention.message}
        </p>

        {/* Action step highlight box */}
        {intervention.action_step && (
          <div className="mb-4 p-2.5 rounded-xl bg-indigo-950/30 border border-indigo-500/20 text-indigo-300 text-xs flex items-start gap-2">
            <span className="font-bold text-indigo-400 flex-shrink-0">Hành động vi mô (5 phút):</span>
            <span className="text-slate-300">{intervention.action_step}</span>
          </div>
        )}

        {/* Feedback Section */}
        <div className="pt-3 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex items-center gap-1.5 text-slate-400">
            <Sparkles className="w-3.5 h-3.5 text-amber-400" />
            <span>Gợi ý này có ích với bạn không?</span>
          </div>

          <div className="flex items-center gap-1.5">
            {/* Helpful button */}
            <button
              type="button"
              disabled={isUpdating}
              onClick={() => handleFeedback('helpful')}
              className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-lg border transition-all ${
                currentResponse === 'helpful'
                  ? 'bg-emerald-500/20 border-emerald-500/40 text-emerald-300 font-semibold'
                  : 'border-slate-800 text-slate-400 hover:text-slate-200 hover:bg-slate-800/60'
              }`}
            >
              <ThumbsUp className="w-3 h-3" />
              <span>Có ích</span>
              {currentResponse === 'helpful' && <Check className="w-3 h-3 ml-0.5" />}
            </button>

            {/* Not helpful button */}
            <button
              type="button"
              disabled={isUpdating}
              onClick={() => handleFeedback('not_helpful')}
              className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-lg border transition-all ${
                currentResponse === 'not_helpful'
                  ? 'bg-rose-500/20 border-rose-500/40 text-rose-300 font-semibold'
                  : 'border-slate-800 text-slate-400 hover:text-slate-200 hover:bg-slate-800/60'
              }`}
            >
              <ThumbsDown className="w-3 h-3" />
              <span>Chưa phù hợp</span>
            </button>

            {/* Dismissed button */}
            <button
              type="button"
              disabled={isUpdating}
              onClick={() => handleFeedback('dismissed')}
              className={`p-1 rounded-lg text-slate-500 hover:text-slate-300 hover:bg-slate-800/60 transition-colors ${
                currentResponse === 'dismissed' ? 'opacity-40' : ''
              }`}
              title="Bỏ qua gợi ý"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
